### ISSUE TITLE
What should coercion look like for R7?

### ISSUE THREAD

**Issue by hadley** [RConsortium/OOP-WG#136]

**Comment by lawremi** [comment]
How about it behaves like `methods::as()` but with a verb like `cast()`? Ideally `cast()` would itself be a generic, with special behavior, so we can avoid the `as()`/`coerce()` duality.

Note that this would be distinct from up casting for affecting dispatch, such as when calling the next method, because casting to affect dispatch should only modify the class, not the structure (so that any extra fields are carried along), and the class modification must be transient so that any dispatch in the next method behaves correctly.

**Comment by hadley** [comment]
I think the challenge of avoiding two functions is that you want to write `cast(object, class)` but dispatch on `class, object_class(object))`.

**Comment by hadley** [comment]
(Note to self: remember to also incorporate `r7_data()` into this)

**Comment by lawremi** [comment]
Agreed that the dispatch behavior is weird, but we can implement `cast()` as a non-standard generic to achieve that.

**Comment by hadley** [comment]
Very initial thoughts:

```R
cast <- R7_generic("coerce", c("from", "to"), function(from, to, ...) {
  signature <- list(class, object_class(object))
  cast <- method(cast, signature)
  cast(object, ...)
})
```
