### ISSUE TITLE
Modification of object property inside function does not modify object property

### ISSUE THREAD

**Issue by ElianHugh** [RConsortium/OOP-WG#246]
Hi there, I've recently started trying out R7 and have run into an issue when attempting to modify a list property via a generic function. Apologies in advance if this is the wrong place for this. Thank you!

Here is the reprex of the issue I'm having:

``` r
library(R7)

emitter <- new_class(
    "emitter",
    properties = list(
        listeners = class_list
    )
)

on <- new_generic("on", "x", function(x, event_name, fn) {
            R7_dispatch()
        }
    )

method(on, emitter) <- function(x, event_name, fn) {
    out <- append(x@listeners[[event_name]], fn)
    x@listeners[[event_name]] <- out
}

x <- emitter()

# modifying through the generic doesn't save the state
on(x, "data", print)
print(length(x@listeners))
#> [1] 0


# modifying the list directly works
x@listeners[['data']] <- append(x@listeners[['data']], print)
print(length(x@listeners))
#> [1] 1
```

<sup>Created on 2022-08-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

My expectation was that objects would be pass by reference (similar to R6), and by extension modifying an object's properties in a closure would modify the original object.

**Comment by hadley** [comment]
This doesn't work because lists areimmutable; i.e. whenever you think you're modifying one, you're actually creating a modified copy. This is the same way that S3 and S4 work, but we haven't explained it anywhere here.

One way work to work around the issue in your case is to use an environment instead of a list:

``` r
library(R7)

emitter <- new_class("emitter",
  properties = list(
    listeners = class_environment
  )
)

on <- new_generic("on", "x", function(x, event_name, fn) {
  R7_dispatch()
})

method(on, emitter) <- function(x, event_name, fn) {
  x@listeners[[event_name]] <- append(x@listeners[[event_name]], fn)
  invisible(x)
}

x <- emitter()
names(x@listeners)
#> character(0)
on(x, "data", print)
#> <emitter>
#>  @ listeners:<environment: 0x7fc92d85eed8>
names(x@listeners)
#> [1] "data"
```

<sup>Created on 2022-08-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I wouldn't 100% recommend this yet, as we haven't fully thought through the consequences of using environment inside R7 objects.

**Comment by ElianHugh** [comment]
Hi Hadley, thank you for the quick response! With regard to mutable state, is it expected that this will be the functionality going forward with R7 properties?

**Comment by hadley** [comment]
@ElianHugh no
