### ISSUE TITLE
Named list of property-specific validators in class constructor

### ISSUE THREAD

**Issue by mattwarkentin** [RConsortium/OOP-WG#251]
Hi,

I just watched the great talk at rstudio::conf(2022) and started playing around with `R7` a bit.

I was wondering if it perhaps makes any sense for the `validator` argument to `new_class()` to be either a single function that globally validates or alternatively a named-list of functions where each name corresponds to an item in `properties`?

Something like:

```r
range <- new_class("range",
  properties = list(
    start = class_double, 
    end = class_double
  ),
  validator = list(
    start = function(self) {
      if (length(self@start) != 1) {
        "@start must be length 1"
      } else if (self@end < self@start) {
        "@start must be less than or equal to @end"
      }
    },
    end = function(self) {
      if (length(self@end) != 1) {
        "@end must be length 1"
      } else if (self@end < self@start) {
        "@end must be greater than or equal to @start"
      }
    }
  )
)
```

This specific example may not be particularly motivating. But it has the advantage of modularity, where you visually see which part of the class constructor code validates which property, and each validation step becomes simpler to maintain (I *think*). 

Also, when only a single property is modified, such as:
```r
x <- range(start = 1, end = 10)
x@start <- 20
```
Only the `validator` for `start` would need to be called, so perhaps a tiny performance advantage over a global validator. 

I am not an expert in OOP by any means, so maybe this is not a reasonable question.

**Comment by jl5000** [comment]
What about if a validation check needs to occur on a combination of values simultaneously? This partitioning then breaks down.

**Comment by jl5000** [comment]
Actually, I've just realised after watching Hadley's presentation again that you could probably do this in the existing implementation. You could ignore the validator function and instead write a setter which includes the validation code for that property. That might work.

**Comment by lawremi** [comment]
Since validation logic can be complex, it's generally a good idea to modularize validation functions; for example a common pattern in S4 is something like:
```
validator <- function(object) {
  c(validator_x(object), validator_y(object))
}
```
which works because `c()` will drop `NULL` values and even return `NULL` when all of the arguments are `NULL`. In principle, this even allows reuse of validation logic across classes, although that might not be common in practice.

I'm not sure there are many advantages to directly supporting per-property validation in the framework itself. It is more self-documenting, but since there would be no easy way to enforce the single-property behavior, it could become incorrect and misleading. Also, there's no way to know which property needs to be checked upon object modification, since the validity of a property can depend on the value of other properties. A compiler approach is a potential path to optimization here.

It would be interesting to think about ways to simplify validation code, since it can be quite verbose, but the verbosity could be considered a feature, since the validator is an important aspect of a class's documentation (as code).

**Comment by jl5000** [comment]
Funnily enough, the c() trick is precisely what I have been doing in my project. However, I'm not entirely pleased with it as it runs all validation code instead of bombing out at the first error (like Hadley's examples). I'm trying to think of a way of reusing my validation functions without having to laboriously write out `if() else ()` statements.

**Comment by lawremi** [comment]
Great. Sometimes running all of the validation code is a good thing. The more information about a failure, the better.  Validation failures should really only be visible to developers, with defensive programming ensuring that user code fails earlier.
