### ISSUE TITLE
Where do the arguments for the method specification live?

### ISSUE THREAD

**Issue by hadley** [RConsortium/OOP-WG#29]
Say we want to define a `mean()` method for class `A`.  Assuming a hypothetical `method<-` function that we use to modify the global methods table, I think there are three ways we could supply the data: 

```R
method(mean, A) <- newMethod(function(x) 10)
# which could be shortened to 
method(mean, A) <- function(x) 10

method(mean) <- newMethod("A", function(x) 10)

methods() <- newMethod("mean", "A", function(x) 10)
```

(We could also do `methods(A) <- newMethod("mean", function(x) 10)` but I think that encourages the wrong mental model of the OO system)

I'm kind of partial to the first, because it means that we wouldn't need to have a user facing method constructor. But either way, I think we need to consider the design of the method/class/generic constructors in tandem with the assignment function that they use to have an impact on the state of the world.

**Comment by lawremi** [comment]
Agreed it's worth continuing this discussion. Are the name and signature intrinsic to the object, or are those associated with the function through a registry? If the user retrieves a method definition, should that definition know the generic name or even directly reference the generic object? Or should the user retrieve a data.frame that binds them together, similar to the return value of `methods()`? 

Having self-contained objects has proven somewhat useful in the methods package, but it has also added a lot of complexity, because it's a pain keeping everything in sync. S3 has obviously gone the lightweight registry route, and we should strongly consider sticking with that. In the short term, it would be wise to avoid exposing any API that would lock us into formal method objects.

This is my favorite of the proposals:
```
method(mean, A) <- function(x) 10
```

It's similar to the syntactic sugar proposed in the spec
```
mean$A <- function(x) 10
```
which best resembles the S3 syntax (which is still supported, of course).

**Comment by hadley** [comment]
I like the idea of putting most of the logic in the registry; I think that reinforces that methods are just functions. 

That's API is my favourite too. What would nested dispatch look like?

```R
method(mean, A, B) <- function(x, y) 10
# or
method(mean, list(A, B)) <- function(x, y) 10
```

(And presumable "A" and "B" would also work, looking for an name bound to a class definition in the enclosing scope)

**Comment by lawremi** [comment]
Could support both. Internally, we would probably use a `Signature` object to store the list of classes. For the sake of clarity, we could expose that here, by pulling up and modifying `methods::signature()`. Like,

```R
method(mean, signature(A, B)) <- function(x, y) 10
```

Then it's obvious to the reader. Could still support the single class and list cases.

**Comment by hadley** [comment]
I think we need to either pick `...` or a single `signature` argument. I think if there's any doubt, it's better to have a single arg and leave dots for future extensions. Then we'd just need something like this to handle the various inputs:

```R
as_signature <- function(x) UseMethod("as_signature")
as_signature.classObject <- function(x) signature(x)
as_signature.list <- function(x) do.call(signature, x)
as_signature.signature <- function(x) x
as_signature.character <- function(x) {
  as_signature(lapply(x, classFind, env = parent.frame()))
}
```

**Comment by lawremi** [comment]
Yes, seems like a good place to start.

**Comment by lawremi** [comment]
Ready to add to the spec?
