### ISSUE TITLE
Package title

### ISSUE THREAD

**Issue by hadley** [RConsortium/OOP-WG#308]
What should it be? Best we came up with in the meeting is:

```yaml
Title: An Object Oriented System Designed to be a Successor to S3 and S4
```

**Comment by lawremi** [comment]
Another option: "An Object Oriented System that Extends S3 with Features Partially Inspired by S4". That speaks more to the compatibility with the existing systems.

**Comment by mmaechler** [comment]
I'd prefer @lawremi 's direction, as it sounds less controversial or sensational.  At least around here, maybe more generally, this would rather help gaining momentum and much less antagonize S3 or S4 lovers (or scare people into thinking R would loose a lot of its very long time stability - very important in many environments). 
... and then, given reality, let's hope most new and many existing projects will adopt it eventually,
but my guess is S3 and S4 will stay with us for a *long* time even when it hindsight maybe only transitionally.

**Comment by mmaechler** [comment]
I understand @hadley's "YA OOP" fear.    Maybe somewhere in between *and* shorter
      __An Object Oriented System Combining S3 and S4__

We are talking about the `DESCRIPTION`  file's `Title: .... ` line,  right?  Maybe we treat `Title: ..`  and `Description: ..`  jointly here? 
Ideally we'd have the `Description: ` section immediately following the `Title: ` (tweaking Roxygen?)   and hence immediately explain what the "Combining" in the title means, possibly by using @lawremi 's __S7 extends S3 with features inspired by S4__ (and maybe even here mention __using a new R-like syntax__  as well.   
Also here (in the `Description: ` paragraph)   I'd use slightly modestly   _meant to become_ instead of _designed to be_  ... but then I'm surely not the expert on English writing style.

**Comment by mmaechler** [comment]
On the package page on CRAN  (and also in r-universe)  the display is always

    <pkg>:  <title>           (1 line "title font")
    <description>             (1 paragraph; often more than one line)

so what I say above makes  sense even if you don't get `Description: ` immediately after `Title: ` in the `DESCRIPTION` file.

**Comment by hadley** [comment]
How about we take @mmaechler's wording tweak from the blog post and make it "An Object Oriented System Meant to Become a Successor to S3 and S4"?

For context, here's the longer description, which I took from the intro to the README:

> A new object oriented programming system designed to be a successor 
  to S3 and S4. It includes formal class, generic, and method specification, 
  and a limited form of multiple dispatch. It has been designed and implemented 
  collaboratively by the R Consortium Object-Oriented Programming Working Group, 
  which includes representatives from R-Core, 'Bioconductor', 
  'Posit'/'tidyverse', and the wider R community.

It looks like the first sentence is redundant with the title (whichever we choose) so maybe would be better as:

> S7 includes formal class, generic, and method specification, 
  and a limited form of multiple dispatch. It has been designed and implemented 
  collaboratively by the R Consortium Object-Oriented Programming Working Group, 
  which includes representatives from R-Core, 'Bioconductor', 
  'Posit'/'tidyverse', and the wider R community.

**Comment by mmaechler** [comment]
You did not change the DESCRIPTION yet (-> relevant for #307)

**Comment by hadley** [comment]
Thanks for the reminder!
