### ISSUE TITLE
Message passing OOP

### ISSUE THREAD

**Issue by wlandau** [RConsortium/OOP-WG#39]
MP OOP occasionally comes up, so I think it deserves a thread. Here are my initial thoughts.

## Questions

1. Will we eventually extend the new system to something that supports MP OOP?
2. If so, what will happen to existing implementations, particularly R6?

## Mutability

I strongly believe we should retain mutability by default in R6 and at least permit mutability in new systems. Mutability is important to MP OOP as a paradigm, and I think immutability would break R6 and downstream packages like `shiny`.

### Efficiency

We have the opportunity to make MP OOP much more efficient in R. In R6, each new object creates deep copies of all the methods. We can fix this with global method registration.

``` r
library(pryr)
#> Registered S3 method overwritten by 'pryr':
#>   method      from
#>   print.bytes Rcpp
library(txtq)
object1 <- txtq(tempfile()) # R6 object
object2 <- txtq(tempfile())
method1 <- object1$push
method2 <- object2$push
address(method1) == address(method2) # Methods are deep copies in objects.
#> [1] FALSE
object_size(object1)
#> 145 kB
object_size(replicate(1e3, txtq(tempfile())))
#> 5.57 MB
```

<sup>Created on 2020-10-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I found the above behavior extremely limiting in [`targets`](https://github.com/wlandau/targets). R6 is a perfect fit to express the infrastructure of a Make-like pipeline tool, but because of the memory inefficiency issue, I cannot use it everywhere. The current implementation has a hybrid of S3 and R6 to make the appropriate tradeoffs. The S3 objects in this case still need to be mutable, so they are environments. That's awkward because they really should be MP OO objects.

[`torch`](https://github.com/mlverse/torch) ran into a similar problem. Object instantiation was too slow because of all the method copying, so @dfalbel implemented a custom fit-for-purpose class system in https://github.com/mlverse/torch/pull/38.

**Comment by wch** [comment]
I want to clear up some misconceptions here. R6 does not do deep copies of methods. When an R6 object is instantiated, it gets copies of all the methods, and then the enclosing environment for each of the methods is changed. That's what makes `self` and `private` refer to the correct object.

If you do an `.Internal(inspect())` on a method in two R6 objects of the same class, you will see that the body and formals refer to the same underlying object in memory, but the environments differ. (A deep copy would make copies of the body and formals as well.)

FWIW, in a quick test I did, torch's R7 is about 10x faster to instantiate objects compared to R6, but about 5x slower to use them. This is likely due to overhead from the `$.R7` method (and GC due to environments and objects inside of them being created every time `$.R7` is used).
  https://gist.github.com/wch/c680fe265763e1b11fab7e3922a19f6a
From what I can tell, R7 should require less memory for storing many objects, because it doesn't modify the functions at all when the objects are instantiated. Instead, it creates a new wrapper function each time `$` is used on those objects.

**Comment by hadley** [comment]
Given @wch's comments, I think a discussion about message passing OOP is probably out of scope for now. It might be worth bringing up again later when we start to discuss implementation, since the speed of method dispatch has great bearing on how you implement something like R6, and how you balance speed of creation vs speed of usage.

**Comment by wch** [comment]
This is a bit off-topic, but regarding message dispatch speed: If the R6 class is created with `class=FALSE`, the instantiated objects do not have an `class` attribute, and this speeds things up access about 2-3 times because R doesn't even try to look for a `$.foo` method. I've updated the gist with some benchmarks with that option.

**Comment by wlandau** [comment]
@wch, this is all extremely helpful, thanks for explaining and for the benchmarks.

From the [performance vignette](https://r6.r-lib.org/articles/Performance.html), it had originally seemed like we might somehow be able to try a more centralized version of  `FunctionEnvNoClass()`. But given the low level considerations you bring up, it now seems a lot more involved, and I agree to postpone.

To be clear, I still love R6 for its mutable objects, its interface, its efficiency compared to reference classes, and the ease with which it expresses infrastructure that is challenging to write in S3. I hope heavy use of R6 right now does not turn into tech debt later on.
