### ISSUE TITLE
Is serialisation in scope?

### ISSUE THREAD

**Issue by hadley** [RConsortium/OOP-WG#50]
Obviously we can't change this without changes to base R, but is it still worth considering at the design phase? The primary use case is to allows object that use external pointers to be saved and reloaded.

**Comment by hadley** [comment]
(This may intersect with properties too; presumably we'll need to serialise the underlying data store, not the properties themselves)

**Comment by wlandau** [comment]
I do think serialization is worth discussing because it easily leads to special cases. I am thinking of `keras` and `torch` objects, which require their own kind of serialization, as well as high-performant serialization methods that only work with data frames. Large data frames or [unexportable objects](https://cran.r-project.org/web/packages/future/vignettes/future-4-non-exportable-objects.html) could show up in the properties as well as the main object.

What do you think about optional custom serialize/unseralize methods in the class definition?

**Comment by hadley** [comment]
I think if we were to provide custom serialisation it would be through a standard generic.

**Comment by lawremi** [comment]
Another consideration in serialization is evolution of the class structure. Having a way to automatically update objects on deserialization would be convenient. We've already been discussing this for S4.

**Comment by hadley** [comment]
@lawremi that would be cool. I think that perhaps also implies that the `newClass()` should have an optional version argument?
