### ISSUE TITLE
Dispatching on "missing"

### ISSUE THREAD

**Issue by lawremi** [RConsortium/OOP-WG#67]
S4 lets us dispatch on "missing", i.e., an argument in the signature not being provided. This is a somewhat useful feature for multiple dispatch. Should/could we support that in R7?

**Comment by hadley** [comment]
Is there an advantage to providing `NULL` as a default value (which makes it clear that the argument is indeed optional) and then dispatching on that?

**Comment by lawremi** [comment]
One example is `[()`, where `x[i,]` is not the same as `x[i,NULL]`. Another is `IRanges::findOverlaps(pattern, subject)`, where omitting `subject` computes overlaps of `pattern` with itself. Overlaps with `NULL` might intuitively have a different semantic (no overlaps).  Making `subject` default to `pattern` does not work either, because the missing method has arguments past `...` that only make sense in a self comparison. There are of course work arounds, but dispatching on missing has proven convenient.

**Comment by mmaechler** [comment]
I strongly agree with @lawremi :  R like optional arguments make sense a lot.   Indexing (*and* subsetting, i.e., the `[<-` generic) semantics in S and R  need this distinction  (and the method implementation in some of my cases in `Matrix` then may additionally use `nargs()` to distinguish cases.. because  there you *also* need to distinguish   `x[i,]` from `x[i]`.

**Comment by hadley** [comment]
I think this is a confusing API (since you can't tell from the function formals which arguments are required and which are optional), but it seems like we'll need it for backward compatibility.

**Comment by lawremi** [comment]
Having this information gives us the opportunity to automatically clarify argument handling in the generic documentation, so that we do not have to depend on the formals and the presence of a default value to communicate optionality.

**Comment by hadley** [comment]
Any syntax preferences for this? We could use `"missing"` or we could make it a special symbol (e.g. `missing_arg`).

(It looks like method dispatch for missing arguments is already implemented, but method registration is not.)

**Comment by lawremi** [comment]
For consistency, what about making something like `missing_arg` be a class object, representing a dummy virtual, final class? That might even simplify the implementation?

**Comment by hadley** [comment]
Yeah, sorry that's what I meant by "special symbol". Does `missing_arg` seem like the right name? Another option would maybe be `r7_missing`? We could also make `missing` work, although it might be a bit confusing since we'd just be using the existing function as a sentinel (like we do for `character`, `integer` etc, but there the connection is much closer).

**Comment by lawremi** [comment]
`missing_arg` seems good enough for now at least.

**Comment by hadley** [comment]
Also need to implement/test dispatch on "ANY", which I think might have gotten muddled up with dispatch on `NULL`.

**Comment by hadley** [comment]
What do you think of "absent" instead of "missing"? It avoids some of the confusion associated with `NA`.

**Comment by hadley** [comment]
I've gone with `missing_class` and `any_class` for now; if needed we can revisit when we look holistically at all the built in class names.
