### ISSUE TITLE
Interface evolution?

### ISSUE THREAD

**Issue by hadley** [RConsortium/OOP-WG#7]
Should we consider the challenge of changing the interface of a generic (i.e. adding or removing arguments, or moving a generic between packages). These are all things that have come up for tidyverse packages, and I don't feel like we have a good solution for them.

Similarly, what about adding attributes to a class? What if, unbeknownst to you, a subclass is already using the attribute you add?

**Comment by lawremi** [comment]
Evolution of generic formals hinges on whether every method needs to have the same formals as its generic (with the "..." affording some flexibility). We should probably immediately state that as a requirement, because the alternative (like Julia, or like overloading in other frameworks) would be really complicated and confusing to users. In Bioconductor, we tend to make our generics extremely... generic... like `function(x, ...)` to maximize flexibility, but of course, that strongly limits how much a client can assume about a generic. So no great solutions here either. Moving generics is usually easier to handle, especially if moving up the package hierarchy, and downstream packages use `import()` instead of `importFrom()` (which is often not a great idea in many cases).

Adding attributes to a class is also problematic from the serialization perspective (there have been proposals around supporting deserialization hooks). Field name clashes are infrequent in my experience, but I guess they could be handled by (virtual) grouping fields by class. This type of conflict is called "field hiding" in Java and is handed by qualifying with the `super` keyword. In C++, field references are qualified by the class name, since there is multiple inheritance.

**Comment by hadley** [comment]
Interface evolution is related to #6; if a mismatch only causes a run-time warning (not an R CMD check problem), it's possible to work around any mismatches within the method itself.

**Comment by lawremi** [comment]
Please clarify what you mean. How would we call the method if the arguments do not match? Drop the new arguments? Expect the method implementation to check every argument with `missing()`?

**Comment by hadley** [comment]
Here's the scenario: I've mistakenly created generic `pkgA::foofy(x, y)` and pkgB has implemented `foofy.character(x, y)`. Now in pkgA 2.0.0, I change the signature of the generic to `foofy(x, y, z, ...)` (i.e. adding an argument, and allowing methods to define their own additional arguments). I email the author of pkgB telling them about the problem. Ideally they'd be able to release a version of pkgB that works with pkgA 1.0.0 and 2.0.0, but if they define `foofy.character(x, y, z, ...)` they'll get an error when R CMD check is run with the released version of pkgA. (A rarer problem is that I've defined `barfy(x, y, ...)` and later decided that `y` is unneeded, and I want to remove it.)

I think there are two things that would help:

* Method validation could only check that the generic arguments are a subset of the method arguments (i.e. a method can have arguments that the generic does not)

* The error could only occur at method dispatch (i.e. `R CMD check` shouldn't verify, assuming that this is a problem to be caught by unit tests)

    ``` r
    foo <- function(x, y) UseMethod("foo")
    foo.character <- function(x) "h" 
    
    foo("x")
    #> [1] "h"
    foo("x", "y")
    #> Error in foo.character("x", "y"): unused argument ("y")
    ```

**Comment by lawremi** [comment]
Thanks for the clarification. I think what you're saying is that pkgB could define `foofy.character(x, y, ...)` to work across versions. Makes sense.

Ideally `R CMD check` would not need to do anything, because we'd detect this at method registration time (like how the methods package works), but that depends on how we register methods. The methods package lets methods append arguments as long as the generic function has `...` in its formals. Would that be flexibility enough?

**Comment by hadley** [comment]
@lawremi unfortunately that's not really enough as we manage to continue to accidentally export generics without `...` 😬. The use of `...` is something else we should eventually discuss as it solves one problem, but introduces another (misspelled arguments are silently swallowed)

**Comment by lawremi** [comment]
The swallowing only happens when the method has `...` (and doesn't check). Using `...` on the generic is convenient and safe, as long as we do not require methods to have `...` when the generic does. My understanding is that S3 enforces both to have `...` because argument dropping is (surprisingly) _intended_.

**Comment by hadley** [comment]
If the generic has `...` then I think the method also need to take `...`, at least if your using `NextMethod()`, because a method for a subclass might take arguments that you don't know about.

**Comment by lawremi** [comment]
Good point. We may prefer the behavior of `methods::callNextMethod()`, which lets the method explicitly forward arguments. Usually that's preferred from the readability perspective but it can be annoying when arguments can be missing.

**Comment by hadley** [comment]
@lawremi ah yes, it'd also be worth rethinking some of the magic that `UseMethod()`/`NextMethod()` both do wrt arguments vs. objects in the function environment. I find the precise rules v. hard to remember, and an on going source of surprise.

**Comment by mmaechler** [comment]
> @lawremi unfortunately that's not really enough as we manage to continue to accidentally export generics without `...` grimacing. The use of `...` is something else we should eventually discuss as it solves one problem, but introduces another (misspelled arguments are silently swallowed)

I agree that ideally this should become better than in current S3 --- if that's possible, I dunno...
 The `...` here, only used for generic <-> method argument matching (i.e. allowing the method to have more arguments) could have different syntax (say 4 dots "...."  (or not) *and* / *or only* differnet semantic and maybe could be "non-swallowing", e.g., give warning for extraneous arguments instead of silently dropping them.   
I had tried to do something like that with introducing the `chkDots()` utility into R a while ago.  It's used in some places (also in  `Matrix` I think), but does not really solve the problem..

**Comment by ltierney** [comment]
The notion of a generic function can have two different meanings in R.

In the context of writing code they establish an interface and a protocol. If `foo` is a generic function and you write
```r
for (i in seq_len(length(x)) foo(x, i)
```
then you expect every method for any `x` that might hit this code to take ah additional index argument
and not need anything else. If you had to supply something else if  `x` is of  class `A` and another thing or two if  `x` is of class `B` then that defeats the point of having a generic function. The generic function should define the contract for how it is called, and code using it should be able to rely on that.

Not everything needed for a protocol is handled by the generic function contracts: `length` and `foo` methods need to be consitent so that any `i` in the range `1:length(x)` will work. We don't have a way of expressing that sort of cross-generic contract.  (I forget if something like Eiffel does).

There is another notion of genericity (genericness? whatever) in R: Functions that are generic from an interactive user perspective. `plot` is the classic example. It is nice to know that `plot` is what you use to, well, get a plot. If you want a plot of y against x you an use `plot(x, y)`. To plot a sine curve you can use `plot(sin, 0, 2 * pi)`.  This is much more convenient than having to use, say,  `plot_xy`
for a scatter plot and `plot_function` for a function. Interactive users know perfectly well whether they are plotting `y` against `x` or a sine curve, so the choice of arguments isn't an issue. Using a generic function in code, like the simple loop, is very different.

The coexistence of these two notions of what it means to be generic is part of why we have the `...` issue. Most generic functions that are intended to be used in code should have a fixed set of clearly defined required arguments and, occasionally, some clearly defined optional ones, and methods
should adhere to that contract.

The one scenario I can think of where having some class-specific optional arguments might make sense is when a generic is used in defining a method, where a specific (super)class is known.

**Comment by lawremi** [comment]
In Bioconductor, we've found "telescoping" formal argument lists practically useful for achieving multiple levels of abstraction. It's like an inheritance hierarchy of methods that parallels the class hierarchy. We could enforce that in the single dispatch case.

**Comment by mmaechler** [comment]
> In Bioconductor, we've found "telescoping" formal argument lists practically useful for achieving multiple levels of abstraction. It's like an inheritance hierarchy of methods that parallels the class hierarchy. We could enforce that in the single dispatch case.

Interesting,and seems a neat idea. Can you give a link to (source/..) an example / more details on this?

**Comment by lawremi** [comment]
One simple example is that we have a Ranges class that stores a vector of intervals. The GRanges class extends Ranges to hold _genomic_ intervals, so they have a strand (+/-). We have a lot of generics that correspond to range operations, like `resize()` to change the width. `resize,GRanges()` adds the `ignore.strand` argument since GRanges introduces the notion of strand.

**Comment by hadley** [comment]
* From bioconductor: Another problem is that parts of the class hierarchy might accept the same arguments.
* From base R: many dot-less generics gained dots over time. The distinction is not clear; some functions like equal of numerics needs more arguments, but that's clearly not just interactive usage.

```R
# Should this error?
x <- list(1.5, 1:5, "a")
lapply(x, print, digits = 3)

# What about this? Impossible to know which arguments are supported here
print_all <- function(x, ...) {
  lapply(x, print, ...)
}
```
