### ISSUE TITLE
Brainstorm new syntax

### ISSUE THREAD

**Issue by hadley** [RConsortium/OOP-WG#75]
Would be useful as an additional carrot to get people to use the system.

One idea: https://github.com/RConsortium/OOP-WG/issues/40

**Comment by lawremi** [comment]
I think this points towards a more declarative syntax, which is the only obvious way (to me) to resolve the redundancy of naming (both in the environment and on the object itself) of generics and classes. This would obviously be a major step for R, but so is support for first class OOP. 

This would mean something like:
```
class text(
  parent = "character", 
  constructor = function(text) new Object(.data = text)
)
generic foo(signature = "x")
```

I do like `new` operator idea also.  It's just a bit strange to require assignment, and there is more than just assignment happening, since the name is also being attached to the object. If we're going to go that far, we might as well consider going declarative, like so many other languages.

**Comment by mmaechler** [comment]
hmm... to me it seems, such parser-change requiring syntax  *and* moving away from the    `obj <-  <some>(..)` 
assignment + function call paradigm  would annihilate much of what we have been thinking / implementing till now.

OTOH, it is closer to what I think to remember  Ian Vitek  would have suggested, i.e. using keyword language instead of character string constants (which in R can always be replaced by a character variable .. but then the variable could actually be anything for static code analysis...

Personally, I had hoped we could stay very close to @lawremi 's original proposal/idea of creating R objects only  (typically via assignments)...

**Comment by jimhester** [comment]
This also would preclude any backward compatibility, to me the (small) amount of redundancy in the current approach is an acceptable tradeoff and going this route doesn't seem the right path.

**Comment by hadley** [comment]
Given the downsides of breaking backward compatibility and the lack of a broadly compelling proposal, I'm going to close this issue. We can of course reconsider if anyone comes up with a better idea.
